inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 3.0

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Lint/Debugger:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
